inherit: ../base.yaml
composition:
  mu:
    openness: 0.5
    conscientiousness: 0.5
    extraversion: 0.5
    agreeableness: 0.5
    neuroticism: 0.5
  sigma: 0.05
name: e2q_homog
llm:
  model: Qwen/Qwen2.5-14B-Instruct-AWQ
