inherit: ../base.yaml
composition:
  mu:
    openness: 0.8
    conscientiousness: 0.5
    extraversion: 0.5
    agreeableness: 0.5
    neuroticism: 0.5
  sigma: 0.15
name: e5_openness_high__mem
society:
  memory_k: 20
