inherit: ../base.yaml
composition:
  mu:
    openness: 0.8
    conscientiousness: 0.5
    extraversion: 0.5
    agreeableness: 0.2
    neuroticism: 0.5
  sigma: 0.15
name: e3qwen7_O8_A2
llm:
  backend: vllm
  model: Qwen/Qwen2.5-7B-Instruct-AWQ
  base_url: http://localhost:8000/v1
  max_workers: 8
